import type { Dispatch, SetStateAction } from "react";
import type { ActivePreviewLayer } from "../application/previewMedia";
import type { useAutomaticEditing } from "../desktop/useAutomaticEditing";
import type { useBatchAutoEdit } from "../desktop/useBatchAutoEdit";
import type { useCreativeLibrary } from "../desktop/useCreativeLibrary";
import type { useDesktopActions } from "../desktop/useDesktopActions";
import type { useMobileRemote } from "../desktop/useMobileRemote";
import type { useProjectRecovery } from "../desktop/useProjectRecovery";
import type { EditorCommand } from "../domain/commands";
import type { EditorHistory } from "../domain/history";
import type { CaptionCue, ClipLayout, EditProject, MotionGraphicKind, MotionGraphicPresetSeed, MotionTrack, NormalizedRect, TimelineClip } from "../domain/types";
import type { EditorTheme } from "./theme";
import type { ProjectSession } from "../application/projectSession";
import type { LowerThirdPresetId } from "../application/lowerThirds";

export type TrackingMode = { kind: "new" | "correct"; trackId?: string } | { kind: "podcast"; role: "host" | "guest"; hostTrack?: MotionTrack };

export interface EditorShellProps {
  currentAestheticArtifact?: import("../domain/types").AestheticArtifactBinding;
  history: EditorHistory;
  project: EditProject;
  projectSession: ProjectSession;
  duration: number;
  theme: EditorTheme;
  setTheme: (theme: EditorTheme) => void;
  isDesktop: boolean;
  playhead: number;
  setPlayhead: Dispatch<SetStateAction<number>>;
  seekRevision: number;
  onPlaybackClock: (time: number, seekRevision: number) => void;
  playing: boolean;
  setPlaying: Dispatch<SetStateAction<boolean>>;
  selectedClipId?: string;
  setSelectedClipId: Dispatch<SetStateAction<string | undefined>>;
  selectedCaptionId?: string;
  setSelectedCaptionId: Dispatch<SetStateAction<string | undefined>>;
  selectedClip?: TimelineClip;
  selectedClipAtPlayhead?: TimelineClip;
  selectedCaption?: CaptionCue;
  transitionNeighbors: { before: boolean; after: boolean };
  selectedMotionTracks: EditProject["motionTracks"];
  activeLayers: ActivePreviewLayer[];
  activeAudioLayers: ActivePreviewLayer[];
  runtimeUrls: Record<string, string>;
  status: string;
  setStatus: Dispatch<SetStateAction<string>>;
  trackingMode?: TrackingMode;
  setTrackingMode: Dispatch<SetStateAction<TrackingMode | undefined>>;
  trackingSelection?: NormalizedRect;
  setTrackingSelection: Dispatch<SetStateAction<NormalizedRect | undefined>>;
  trackingBusy: boolean;
  recovery: ReturnType<typeof useProjectRecovery>;
  desktopActions: ReturnType<typeof useDesktopActions>;
  automatic: ReturnType<typeof useAutomaticEditing>;
  creativeLibrary: ReturnType<typeof useCreativeLibrary>;
  batchAutoEdit: ReturnType<typeof useBatchAutoEdit>;
  mobile: ReturnType<typeof useMobileRemote>;
  newProject: () => void;
  openProject: () => Promise<void>;
  saveProject: (saveAs?: boolean) => Promise<void>;
  undoEdit: () => void;
  redoEdit: () => void;
  renderVideo: () => Promise<void>;
  renderOpenExrSequence: () => Promise<void>;
  renderAlphaMaster: () => Promise<void>;
  importFiles: (files: File[]) => Promise<void>;
  acceptTrackingSelection: (rect: NormalizedRect) => Promise<void>;
  startPodcastDirector: () => void;
  submitAgentInstruction: (instruction: string) => void;
  runCommand: (command: EditorCommand, successMessage?: string) => void;
  updateAnimatedClipProperty: (property: "transform" | "color", patch: Record<string, number>) => void;
  addMotionGraphic: (kind: MotionGraphicKind, trackId?: string, seed?: MotionGraphicPresetSeed) => void;
  addCaption: () => void;
  addTrack: (kind: "video" | "audio") => void;
  addAssetToTimeline: (assetId: string, mode?: "timeline" | "pip") => void;
  makeSelectedPictureInPicture: (layout?: ClipLayout, name?: string) => void;
  precomposeSelected: () => void;
  applyShortFormTemplate: (templateId: string) => Promise<void>;
  applyLongFormTemplate: (templateId: string) => Promise<void>;
  addLowerThird: (presetId: LowerThirdPresetId, personName: string, organization: string) => void;
  clearTemplateApplication: () => void;
  splitSelected: () => void;
  deleteSelected: () => void;
}
