import {describe,it,expect} from 'vitest';
import {DEFAULT_COLOR} from '../domain/types';
import {createDemoProject} from '../domain/demo';
import {commonVideoGradeSupported,defaultColor,composeColors,resolveNativeVideoPrecompositions} from './gpuCompositorAdmission';
describe('linear WB native grade boundaries',()=>{
  it('keeps neutral identity and all finite supported independent stops',()=>{expect(defaultColor({...DEFAULT_COLOR})).toBe(true);for(const value of [-4,0,4])expect(commonVideoGradeSupported({...DEFAULT_COLOR,whiteBalanceRed:value})).toBe(true);expect(defaultColor({...DEFAULT_COLOR,whiteBalanceGreen:.1})).toBe(false);});
  it.each([NaN,Infinity,-Infinity,-4.001,4.001])('rejects invalid stop %s',value=>expect(commonVideoGradeSupported({...DEFAULT_COLOR,whiteBalanceBlue:value})).toBe(false));
  it('preserves legacy zero-only composition and rejects unproved nonzero composition',()=>{expect(composeColors({...DEFAULT_COLOR},{...DEFAULT_COLOR})).toEqual(DEFAULT_COLOR);expect(()=>composeColors({...DEFAULT_COLOR,whiteBalanceRed:.25},{...DEFAULT_COLOR,whiteBalanceRed:.25})).toThrow(/proven shared linear domain/);});
  it('rejects WB precomposition without changing original graph; zero still resolves',()=>{const p=createDemoProject();p.width=960;p.height=540;p.assets[0]!.width=960;p.assets[0]!.height=540;p.assets[0]!.uri='C:/fixture/leaf.mp4';const child=structuredClone(p.tracks[0]!.clips[0]!);child.id='nested';child.timelineStart=0;child.duration=2;child.trackId='nested-track';p.compositions.push({schema:'editkin.composition/v1',id:'nested',name:'Nested',width:960,height:540,fps:30,duration:2,tracks:[{id:'nested-track',name:'Nested',kind:'video',locked:false,muted:false,clips:[child]}],captions:[],captionStyle:structuredClone(p.captionStyle),motionTracks:[],motionGraphics:[],director:structuredClone(p.director),updatedAt:p.updatedAt});p.assets.push({id:'nested-asset',name:'Nested',kind:'video',uri:'editkin-composition://nested',compositionId:'nested',duration:2,width:960,height:540});const outer=p.tracks[0]!.clips[0]!;outer.assetId='nested-asset';outer.duration=1;outer.sourceStart=0;expect(resolveNativeVideoPrecompositions(p)).toBeDefined();child.color.whiteBalanceRed=.25;const before=JSON.stringify(p);expect(resolveNativeVideoPrecompositions(p)).toBeUndefined();expect(JSON.stringify(p)).toBe(before);});
});
