import {describe,it,expect} from 'vitest';
import {createDemoProject} from '../domain/demo';
import {buildGpuEngineVideoPreviewGraph} from './gpuCompositor';
import {access} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import {renderResidentSceneLinearVideoSequence} from './residentSceneLinearVideoSequence';
import {INPUT,INPUT_V2,residentSceneLinearInputAtFrame,assertResidentSceneLinearWhiteBalanceReceipt,residentSceneLinearVisualExpectations} from './residentSceneLinearWhiteBalance';
function fixture(wb=true,adjustment=false){const p=createDemoProject();p.width=960;p.height=540;p.assets[0]!.width=960;p.assets[0]!.height=540;p.assets[0]!.uri='C:/fixture/sdr.mp4';p.assets[0]!.color={interpretation:'rec709'};p.captions=[];p.motionGraphics=[];p.colorManagement={...p.colorManagement!,mode:'aces2',outputTransform:'rec709_sdr'};const clip=p.tracks[0]!.clips[0]!;clip.timelineStart=0;clip.duration=1;clip.color.whiteBalanceRed=wb?.5:0;const later=structuredClone(clip);later.id='later';later.timelineStart=1;later.color.whiteBalanceRed=0;p.tracks[0]!.clips.push(later);if(adjustment){const a=structuredClone(clip);a.id='adjust';a.trackId='adjust';a.duration=2;a.layer={enabled:true,blendMode:'normal',role:'adjustment'};a.color.whiteBalanceGreen=.25;p.tracks.push({id:'adjust',name:'Adjust',kind:'video',muted:false,locked:false,clips:[a]});}return buildGpuEngineVideoPreviewGraph(p,0)!.graph;}
function receipt(graph:ReturnType<typeof fixture>,frame:number){const active=(n:any)=>frame>=n.timeline.timelineStartFrame&&frame<n.timeline.timelineStartFrame+n.timeline.durationFrames;const {layers,adjustments}=residentSceneLinearVisualExpectations(graph);return {inputTransform:residentSceneLinearInputAtFrame(graph,frame),layers:layers.filter(x=>active(x.source)).map(x=>({sourceNodeId:x.sourceNodeId,visualGraph:{...(x.grade.grade as object),inputTransfer:x.grade.processor===INPUT_V2?2:1}})),activeAdjustments:adjustments.filter(x=>active(x.adjustment)).map(x=>({nodeIds:x.nodeIds,visualGraph:{...(x.grade.grade as object),inputTransfer:0}}))};}
describe('resident sequence per-visual WB input contract',()=>{
 it('rejects unsupported input before creating output or starting native process',async()=>{const graph=fixture();residentSceneLinearVisualExpectations(graph).layers[0]!.grade.inputSpace='hlg';const outputDirectory=resolve('.rd/linear-white-balance-20260831',`must-not-exist-${randomUUID()}`);await expect(renderResidentSceneLinearVideoSequence({graph,startFrame:0,frameCount:1,executable:'must-never-launch.exe',outputDirectory,assetBindings:{},timeoutMs:1000})).rejects.toThrow(/unsupported/);await expect(access(outputDirectory)).rejects.toThrow();});
 it('uses active frame source contract, not any future/past v2 layer',()=>{const graph=fixture();expect(residentSceneLinearInputAtFrame(graph,0)).toBe(INPUT_V2);expect(residentSceneLinearInputAtFrame(graph,29)).toBe(INPUT_V2);expect(residentSceneLinearInputAtFrame(graph,30)).toBe(INPUT);expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(graph,0,receipt(graph,0))).not.toThrow();expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(graph,30,receipt(graph,30))).not.toThrow();});
 it('keeps old zero v1 receipts without new per-visual fields compatible',()=>{expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(fixture(false),0,{inputTransform:INPUT})).not.toThrow();});
 it.each(['missing','wrong-stop','wrong-transfer','wrong-global','wrong-source'])('rejects %s v2 receipt',mode=>{const graph=fixture(),r=receipt(graph,0);const v=r.layers[0]!.visualGraph as Record<string,unknown>;if(mode==='missing')delete v.whiteBalanceRed;if(mode==='wrong-stop')v.whiteBalanceRed=0;if(mode==='wrong-transfer')v.inputTransfer=1;if(mode==='wrong-global')r.inputTransform=INPUT;if(mode==='wrong-source')r.layers[0]!.sourceNodeId='other';expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(graph,0,r)).toThrow(/receipt/);});
 it('binds linear adjustment gains without falsely changing source input transform',()=>{const graph=fixture(false,true),r=receipt(graph,0);expect(r.inputTransform).toBe(INPUT);expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(graph,0,r)).not.toThrow();r.activeAdjustments[0]!.visualGraph.inputTransfer=2;expect(()=>assertResidentSceneLinearWhiteBalanceReceipt(graph,0,r)).toThrow(/adjustment/);});
 it.each(['hlg','pq','linear_rec709'])('rejects unhandled source input %s',input=>{const graph=fixture();residentSceneLinearVisualExpectations(graph).layers[0]!.grade.inputSpace=input;expect(()=>residentSceneLinearInputAtFrame(graph,0)).toThrow(/unsupported/);});
});
