import {describe,it,expect} from 'vitest';
import {graphSdrNativeSurfaceValid,rec709SdrV2NativeSurfaceValid,activeSceneLinearInputTransform,legacyVideoFallbackAllowed} from './residentGpuPreviewReceipts';
import {createDemoProject} from '../domain/demo';
import {buildGpuEngineVideoPreviewGraph} from '../render/gpuCompositor';
import {buildEngineRenderGraph} from '../render/engineGraph';
import type {GpuNativePreviewSurface} from './types';
import type {ExpectedEngineVideoLayer} from './residentGpuPreviewExpectations';
function graph(wb=true){const p=createDemoProject();p.width=960;p.height=540;p.assets[0]!.width=960;p.assets[0]!.height=540;p.captions=[];p.motionGraphics=[];p.assets[0]!.uri='C:/fixture/sdr.mp4';p.assets[0]!.color={interpretation:'rec709'};p.tracks[0]!.clips[0]!.color.whiteBalanceRed=wb?.5:0;return buildGpuEngineVideoPreviewGraph(p,0)!.graph;}
function surface(v2=true){return {bound:true,backend:'Dx12',nativeSwapChain:true,cpuPixelReadbacks:0,surfaceFormat:v2?'Bgra8Unorm':'Bgra8UnormSrgb',surfaceColorSpace:'Auto',requestedColorSpace:'srgb',pixelContract:v2?'rec709-encoded-sdr-video/v2':'legacy-sdr-video/v1',hdrTransportConfigured:false,legacyVideoPresentationAllowed:true,dxgiColorSpaceConfiguration:'wgpu-dx12-IDXGISwapChain3-SetColorSpace1/v1',physicalDisplayHdrVisibility:'advisory-unverified',displayHdrInfo:{advisoryOnly:true}} as GpuNativePreviewSurface;}
describe('GUI graph-bound SDR v2 surface',()=>{
 it('never selects the old native video route for a v2 graph, even with zero gains',()=>{expect(legacyVideoFallbackAllowed(graph(false))).toBe(false);expect(legacyVideoFallbackAllowed(graph())).toBe(false);expect(legacyVideoFallbackAllowed(buildEngineRenderGraph(createDemoProject()))).toBe(true);expect(legacyVideoFallbackAllowed(undefined)).toBe(true);});
 it('requires encoded Rec709 UNORM on nonzero session; rejects legacy brightening path',()=>{expect(graphSdrNativeSurfaceValid(surface(),graph())).toBe(true);expect(graphSdrNativeSurfaceValid(surface(false),graph())).toBe(false);});
 it('current zero video requires v2 while explicitly legacy low-level graph stays old',()=>{expect(graphSdrNativeSurfaceValid(surface(),graph(false))).toBe(true);expect(graphSdrNativeSurfaceValid(surface(false),graph(false))).toBe(false);const legacy=buildEngineRenderGraph(createDemoProject());expect(graphSdrNativeSurfaceValid(surface(false),legacy)).toBe(true);expect(graphSdrNativeSurfaceValid(surface(),legacy)).toBe(false);});
 it.each([{surfaceFormat:'Bgra8UnormSrgb'},{pixelContract:'legacy-sdr-video/v1'},{cpuPixelReadbacks:1},{surfaceColorSpace:'Bt2100Pq'},{hdrTransportConfigured:true},{nativeSwapChain:false}])('rejects conflicting v2 transport %j',patch=>expect(rec709SdrV2NativeSurfaceValid({...surface(),...patch} as GpuNativePreviewSurface)).toBe(false));
 it('derives input from active sources and referenced matte, not future v2 nodes',()=>{const layers=[{source:{timeline:{timelineStartFrame:0,durationFrames:30}},grade:{processor:'editkin-srgb-to-linear-rec709-primary/v1'}},{source:{timeline:{timelineStartFrame:30,durationFrames:30}},grade:{processor:'editkin-rec709-to-linear-rec709-primary/v2'}}] as unknown as ExpectedEngineVideoLayer[];expect(activeSceneLinearInputTransform(layers,0)).toMatch(/\/v1$/);expect(activeSceneLinearInputTransform(layers,30)).toMatch(/\/v2$/);layers[0]!.matteLayerIndex=1;expect(activeSceneLinearInputTransform(layers,0)).toMatch(/\/v2$/);});
});
