import {describe,it,expect,vi} from "vitest";
vi.mock("react",()=>({useState:(v:unknown)=>[v,vi.fn()],useRef:(current:unknown)=>({current}),useCallback:(f:unknown)=>f,useEffect:()=>{}}));
import {useCreativeLibrary} from "./useCreativeLibrary";
import {createProjectSession} from "../application/projectSession";
import {createDemoProject} from "../domain/demo";
import {dispatchCommand} from "../domain/history";
import type {HaoDesktopApi,PickedMedia,PrepareMediaResult} from "./types";
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function fixture(count=1){const initial=createDemoProject(),session=createProjectSession(initial),items:PickedMedia[]=Array.from({length:count},(_,i)=>({asset:{...initial.assets[0]!,id:`incoming-${i}`,uri:`fixture-${i}.mov`},previewUrl:`raw-${i}.mov`}));const prepared=(item:PickedMedia):PrepareMediaResult=>({assetId:item.asset.id,derivatives:{sourceSha256:"a".repeat(64),generatedAt:new Date(0).toISOString()},runtimeUrls:{[item.asset.id]:`proxy-${item.asset.id}.mp4`},cacheHit:false});const api={pickMedia:vi.fn(async()=>items),importMediaPaths:vi.fn(async()=>items),importCreativeAsset:vi.fn(async()=>items[0]!),prepareMedia:vi.fn(async(asset)=>prepared(items.find(i=>i.asset.id===asset.id)!))};const onPicked=vi.fn((picked:PickedMedia[])=>{session.setHistory(history=>dispatchCommand(history,{type:"batch",commands:picked.flatMap(item=>[{type:"import_asset" as const,asset:item.asset},{type:"add_clip" as const,clip:{...structuredClone(initial.tracks[0]!.clips[0]!),id:`clip-${item.asset.id}`,assetId:item.asset.id,timelineStart:20+items.indexOf(items.find(i=>i.asset.id===item.asset.id)!)*20}}])}));});const onPrepared=vi.fn(),onStatus=vi.fn();const hook=useCreativeLibrary({api:api as unknown as HaoDesktopApi,projectSession:session,onPicked,onPrepared,onStatus,onCommands:vi.fn()});return{initial,session,items,prepared,api,onPicked,onPrepared,onStatus,hook};}
describe("prepared import commit boundary (real hook/store/commands, explicit native/React mocks)",()=>{
 it.each(["picker","drop"])("does not mutate the graph on %s preparation failure and retries only failed work",async route=>{const f=fixture();f.api.prepareMedia.mockRejectedValueOnce(Error("overlay failed after primary"));await(route==="picker"?f.hook.importDesktopMedia():f.hook.importDesktopPaths(["raw.mov"]));expect(f.onPicked).not.toHaveBeenCalled();expect(f.onPrepared).not.toHaveBeenCalled();expect(f.session.getSnapshot().history.present).toBe(f.initial);expect(f.onStatus).toHaveBeenLastCalledWith(expect.stringContaining("尚未加入時間軸"));await f.hook.retryFailedImports();expect(f.onPicked).toHaveBeenCalledTimes(1);expect(f.onPicked.mock.calls[0]![0][0]).toMatchObject({previewUrl:"proxy-incoming-0.mp4",asset:{uri:"fixture-0.mov",derivatives:{sourceSha256:"a".repeat(64)}}});});
 it.each(["public","private"])("adds verified %s library media immediately and retries background optimization without duplicating the clip",async route=>{const f=fixture();f.api.prepareMedia.mockRejectedValueOnce(Error("proxy failed"));await f.hook.importCreativeAsset(route+":fixture");expect(f.onPicked).toHaveBeenCalledTimes(1);expect(f.onPicked.mock.calls[0]![0][0]).toMatchObject({previewUrl:"raw-0.mov",asset:{uri:"fixture-0.mov"}});expect(f.onPrepared).not.toHaveBeenCalled();await flush();expect(f.onStatus).toHaveBeenLastCalledWith(expect.stringContaining("素材已在時間軸"));await f.hook.retryFailedImports();expect(f.onPicked).toHaveBeenCalledTimes(1);expect(f.onPrepared).toHaveBeenCalledExactlyOnceWith([f.prepared(f.items[0]!)]);});
 it.each(["missing-url","wrong-id"])("rejects malformed result %s without raw fallback",async mode=>{const f=fixture();f.api.prepareMedia.mockResolvedValueOnce({...f.prepared(f.items[0]!),...(mode==="missing-url"?{runtimeUrls:{}}:{assetId:"other"})});await f.hook.importDesktopMedia();expect(f.onPicked).not.toHaveBeenCalled();expect(f.session.getSnapshot().history.present).toBe(f.initial);});
 it("bounds preparation to2, commits valid subset once in source order, retries no successful item",async()=>{const f=fixture(5),releases:Array<()=>void>=[];let active=0,max=0;f.api.prepareMedia.mockImplementation(asset=>new Promise((resolve,reject)=>{active++;max=Math.max(max,active);releases.push(()=>{active--;if(asset.id==="incoming-1")reject(Error("unsupported"));else resolve(f.prepared(f.items.find(i=>i.asset.id===asset.id)!));});}));const run=f.hook.importDesktopMedia();await flush();expect(releases).toHaveLength(2);expect(f.onPicked).not.toHaveBeenCalled();for(let i=0;i<5;i++){releases[i]!();await flush();}await run;expect(max).toBe(2);expect(f.onPicked).toHaveBeenCalledTimes(1);expect(f.onPicked.mock.calls[0]![0].map(i=>i.asset.id)).toEqual(["incoming-0","incoming-2","incoming-3","incoming-4"]);f.api.prepareMedia.mockImplementation(async asset=>f.prepared(f.items.find(i=>i.asset.id===asset.id)!));await f.hook.retryFailedImports();expect(f.onPicked.mock.calls[1]![0].map(i=>i.asset.id)).toEqual(["incoming-1"]);expect(f.api.prepareMedia).toHaveBeenCalledTimes(6);});
 it("does not commit after same-id session replacement or permit duplicate imports",async()=>{const f=fixture();let release!:(p:PrepareMediaResult)=>void;f.api.prepareMedia.mockImplementation(()=>new Promise(resolve=>release=resolve));const run=f.hook.importDesktopMedia();await flush();await f.hook.importDesktopMedia();expect(f.api.pickMedia).toHaveBeenCalledTimes(1);f.session.replaceProject({...f.initial,name:"New session"});release(f.prepared(f.items[0]!));await run;expect(f.onPicked).not.toHaveBeenCalled();});
 it("preserves same-session edits while preparing and does not retry into a new session",async()=>{const f=fixture();f.api.prepareMedia.mockRejectedValueOnce(Error("failed"));await f.hook.importDesktopMedia();f.session.replaceProject({...f.initial,name:"Keep new"});await f.hook.retryFailedImports();expect(f.api.prepareMedia).toHaveBeenCalledTimes(1);expect(f.onPicked).not.toHaveBeenCalled();});
});
