import {expect,it} from "vitest";
import {mkdtemp,mkdir,writeFile,readFile,symlink} from "node:fs/promises";
import {resolve,join} from "node:path";
import {buildMaterialColorBundle} from "./lib/material-color-bundle-identity.mjs";
async function fixture(){const parent=resolve(".rd/tmp");await mkdir(parent,{recursive:true});const root=await mkdtemp(join(parent,"color-build-guard-")),source=join(root,"src/application");await mkdir(source,{recursive:true});await writeFile(join(source,"materialColorImplementationPaths.json"),JSON.stringify(["module.ts"]));await writeFile(join(source,"module.ts"),"export const sample = 1;\n");const outfile=join(root,"output.mjs");await writeFile(outfile,"owned-previous-output");return {root,source,outfile};}
it("rejects split builds before replacing an existing output",async()=>{const f=await fixture();await expect(buildMaterialColorBundle({absWorkingDir:f.root,stdin:{contents:"console.log(1)"},outfile:f.outfile,splitting:true})).rejects.toThrow("single-esm");expect(await readFile(f.outfile,"utf8")).toBe("owned-previous-output");});
it.each(["traversal","duplicate","unknown-file"])("rejects %s source registry without artifact mutation",async mode=>{const f=await fixture();const list=mode==="traversal"?["../../../outside.ts"]:mode==="duplicate"?["module.ts","module.ts"]:["missing.ts"];await writeFile(join(f.source,"materialColorImplementationPaths.json"),JSON.stringify(list));await expect(buildMaterialColorBundle({absWorkingDir:f.root,stdin:{contents:"console.log(1)"},outfile:f.outfile})).rejects.toThrow();expect(await readFile(f.outfile,"utf8")).toBe("owned-previous-output");});
it("rejects ancestor alias escaping source root",async()=>{const f=await fixture(),outside=join(f.root,"outside");await mkdir(outside);await writeFile(join(outside,"module.ts"),"outside-evidence");await symlink(outside,join(f.source,"alias"),process.platform==="win32"?"junction":"dir");await writeFile(join(f.source,"materialColorImplementationPaths.json"),JSON.stringify(["alias/module.ts"]));await expect(buildMaterialColorBundle({absWorkingDir:f.root,stdin:{contents:"console.log(1)"},outfile:f.outfile})).rejects.toThrow("aliased-material");expect(await readFile(join(outside,"module.ts"),"utf8")).toBe("outside-evidence");expect(await readFile(f.outfile,"utf8")).toBe("owned-previous-output");});
it("refuses input drift during esbuild rather than refreshing failed output hashes",async()=>{const f=await fixture();await expect(buildMaterialColorBundle({absWorkingDir:f.root,stdin:{contents:"console.log(1)"},outfile:f.outfile,plugins:[{name:"owned-drift-control",setup(b){b.onEnd(async()=>{await writeFile(join(f.source,"module.ts"),"export const sample = 2;\n");});}}]})).rejects.toThrow("build-input-drift");expect(await readFile(f.outfile,"utf8")).toBe("owned-previous-output");});
