param(
  [Parameter(Mandatory = $true)][string[]]$Names,
  [switch]$Apply
)
$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')).TrimEnd('\')
if ([IO.Path]::GetFileName($projectRoot) -ne 'editkin-autopilot') { throw 'Unexpected project directory' }
$artifactRoot = [IO.Path]::GetFullPath((Join-Path $projectRoot '..\artifacts\autopilot-desk')).TrimEnd('\')
function Assert-RegularPath([string]$Path, [bool]$Directory) {
  $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
  if ($item.PSIsContainer -ne $Directory -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
    throw 'Cleanup path must be a regular file or directory'
  }
  return $item
}
$null = Assert-RegularPath $artifactRoot $true
function Assert-ReviewStopped([string]$Root, [int]$AppPid, [string]$Executable = '') {
  # Windows reuses PIDs. A recorded native preview PID now owned by another
  # executable name cannot be that original app. Legacy reports without native
  # executable evidence retain the conservative PID-only protection.
  $nativeEvidence = $Executable -and [IO.Path]::IsPathRooted($Executable) -and
    [IO.Path]::GetFileName($Executable) -eq 'AutopilotDesk-Community-Preview.exe'
  $live = @(Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object {
    ($AppPid -gt 0 -and $_.ProcessId -eq $AppPid -and (-not $nativeEvidence -or $_.Name -eq 'AutopilotDesk-Community-Preview.exe')) -or
    ($_.CommandLine -and $_.CommandLine.IndexOf($Root, [StringComparison]::OrdinalIgnoreCase) -ge 0)
  })
  if ($live.Count -gt 0) { throw 'A review process still exists; no cache may be deleted' }
}
function Get-CacheFiles([string]$Root) {
  $null = Assert-RegularPath $Root $true
  $items = @(Get-ChildItem -LiteralPath $Root -Recurse -Force -ErrorAction Stop)
  if (@($items | Where-Object { $_.Attributes -band [IO.FileAttributes]::ReparsePoint }).Count -gt 0) {
    throw 'Cache contains a reparse point'
  }
  return @($items | Where-Object { -not $_.PSIsContainer })
}
$plans = @()
foreach ($name in ($Names | Select-Object -Unique)) {
  if ($name -notmatch '^(agent-binding-review|agent-caption-(review|live)|native-agent-review|caption-correction-review|packaged-asr-review|editor-project-review|cache-prune-self-test)-[A-Za-z0-9]+$') {
    throw 'Only explicitly named desktop review directories are accepted'
  }
  $root = [IO.Path]::GetFullPath((Join-Path $artifactRoot $name))
  if ([IO.Path]::GetDirectoryName($root) -ne $artifactRoot) { throw 'Review escaped artifact root' }
  $null = Assert-RegularPath $root $true
  $reportPath = Join-Path $root 'report.json'
  $null = Assert-RegularPath $reportPath $false
  $report = Get-Content -LiteralPath $reportPath -Raw -Encoding UTF8 | ConvertFrom-Json
  if ($report.status -notin @('PASS', 'BLOCK', 'REPRODUCED_UNDO_PER_KEYSTROKE')) { throw 'Review has not finished' }
  if (-not $report.PSObject.Properties['appPid']) { throw 'Review has no owned application PID evidence' }
  Assert-ReviewStopped $root ([int]$report.appPid) $report.executable
  $cache = [IO.Path]::GetFullPath((Join-Path $root 'webview2'))
  if ([IO.Path]::GetDirectoryName($cache) -ne $root) { throw 'Cache escaped review directory' }
  if (-not (Test-Path -LiteralPath $cache)) { continue }
  $files = @(Get-CacheFiles $cache)
  $bytes = [long](($files | Measure-Object Length -Sum).Sum)
  $plans += [pscustomobject]@{ name = $name; appPid = [int]$report.appPid; executable = $report.executable; reportStatus = $report.status;
    cache = 'webview2'; files = $files.Count; bytes = $bytes; reportSha256 = (Get-FileHash -LiteralPath $reportPath -Algorithm SHA256).Hash.ToLowerInvariant() }
}
$total = [long](($plans | Measure-Object bytes -Sum).Sum)
if (-not $Apply) {
  [pscustomobject]@{ status = 'dry-run'; count = $plans.Count; bytes = $total; plans = $plans } | ConvertTo-Json -Depth 5
  exit 0
}
$manifestPath = Join-Path $artifactRoot ('review-cache-prune-' + [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '.json')
$manifest = [ordered]@{ schema = 'editkin-review-cache-cleanup/v2'; createdAtUtc = [DateTime]::UtcNow.ToString('o');
  scope = 'explicit completed review WebView2 caches'; recovery = 'regenerated by review scripts; reports, projects, media and app data retained';
  planned = $plans; deleted = @(); reclaimedBytes = [long]0; status = 'running' }
function Save-Manifest { $manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding UTF8 }
Save-Manifest
try {
  foreach ($plan in $plans) {
    $root = [IO.Path]::GetFullPath((Join-Path $artifactRoot $plan.name))
    if ([IO.Path]::GetDirectoryName($root) -ne $artifactRoot) { throw 'Review escaped artifact root before deletion' }
    $null = Assert-RegularPath $root $true
    Assert-ReviewStopped $root $plan.appPid $plan.executable
    $cache = [IO.Path]::GetFullPath((Join-Path $root 'webview2'))
    if ([IO.Path]::GetDirectoryName($cache) -ne $root) { throw 'Cache escaped review before deletion' }
    $files = @(Get-CacheFiles $cache)
    if ($files.Count -ne $plan.files -or [long](($files | Measure-Object Length -Sum).Sum) -ne $plan.bytes) {
      throw 'Cache changed after inventory'
    }
    $reportPath = Join-Path $root 'report.json'
    if ((Get-FileHash -LiteralPath $reportPath -Algorithm SHA256).Hash.ToLowerInvariant() -ne $plan.reportSha256) { throw 'Review report changed' }
    Remove-Item -LiteralPath $cache -Recurse -Force -ErrorAction Stop
    if (Test-Path -LiteralPath $cache) { throw 'Cache deletion did not finish' }
    if ((Get-FileHash -LiteralPath $reportPath -Algorithm SHA256).Hash.ToLowerInvariant() -ne $plan.reportSha256) { throw 'Review report was not preserved' }
    $manifest.deleted += $plan.name
    $manifest.reclaimedBytes += $plan.bytes
    Save-Manifest
  }
  $manifest.status = 'complete'; Save-Manifest
} catch { $manifest.status = 'partial'; Save-Manifest; throw }
[pscustomobject]@{ status = $manifest.status; manifestPath = $manifestPath; deleted = $manifest.deleted.Count; reclaimedBytes = $manifest.reclaimedBytes } | ConvertTo-Json -Compress
