import { createHash } from "node:crypto";
import { readFile, stat } from "node:fs/promises";

const sha256 = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");

export async function buildTemporalLookProjectReport(context: Record<string, any>): Promise<Record<string, any>> {
  const {
    adjustmentDelta, filteredProject, losslessPixelDifferences, materializedClipReset, mixed,
    multiAdjustmentLosslessPixelDifferences, multiAdjustmentMixed, multiAdjustmentPlanSuppressed, multiAdjustmentProjectSuppressed, multiAdjustmentSourceProjectImmutable,
    multiAdjustmentWorker, multiOverlayLosslessPixelDifferences, multiOverlayMixed, multiOverlayPlanSuppressed, multiOverlayProjectSuppressed,
    multiOverlaySourceProjectImmutable, multiOverlayWorker, overlayDelta, overlayLosslessPixelDifferences, overlayMixed,
    overlayPlanSuppressed, overlayProjectSuppressed, overlaySourceProjectImmutable, overlayWorker, partialFilteredProject,
    partialMixed, partialOverlayDelta, partialOverlayInactivePixelDifferences, partialOverlayLosslessPixelDifferences, partialOverlayProjectTail,
    partialSourceSnapshot, partialWorker, particleAnimatedOverlayLosslessPixelDifferences, particleAnimatedOverlayMixed, particleAnimatedOverlayPlanSuppressed,
    particleAnimatedOverlayProjectSuppressed, particleAnimatedOverlaySourceProjectImmutable, particleAnimatedOverlayTransformDelta, particleAnimatedOverlayWorker, particleDelta,
    particleLosslessPixelDifferences, particleMixed, particleMultiAdjustmentLosslessPixelDifferences, particleMultiAdjustmentMixed, particleMultiAdjustmentPlanSuppressed,
    particleMultiAdjustmentProjectSuppressed, particleMultiAdjustmentSourceProjectImmutable, particleMultiAdjustmentWorker, particleOverlayLosslessPixelDifferences, particleOverlayMixed,
    particleOverlayMultiAdjustmentLosslessPixelDifferences, particleOverlayMultiAdjustmentMixed, particleOverlayMultiAdjustmentPlanSuppressed, particleOverlayMultiAdjustmentProjectSuppressed, particleOverlayMultiAdjustmentSourceProjectImmutable,
    particleOverlayMultiAdjustmentWorker, particleOverlayParticleDelta, particleOverlayPlanSuppressed, particleOverlayProjectSuppressed, particleOverlaySecondAdjustmentDelta,
    particleOverlaySourceProjectImmutable, particleOverlayVideoDelta, particleOverlayWorker, particlePartialMixed, particlePartialOverlayInactivePixelDifferences,
    particlePartialOverlayLosslessPixelDifferences, particlePartialOverlayMultiAdjustmentLosslessPixelDifferences, particlePartialOverlayMultiAdjustmentMixed, particlePartialOverlayMultiAdjustmentPlanSuppressed, particlePartialOverlayMultiAdjustmentProjectSuppressed,
    particlePartialOverlayMultiAdjustmentProjectTail, particlePartialOverlayMultiAdjustmentSegmentFramesInside, particlePartialOverlayMultiAdjustmentSourceProjectImmutable, particlePartialOverlayMultiAdjustmentWorker, particlePartialOverlayParticleDelta,
    particlePartialOverlayPlanSuppressed, particlePartialOverlayProjectSuppressed, particlePartialOverlayProjectTail, particlePartialOverlaySecondAdjustmentDelta, particlePartialOverlaySourceProjectImmutable,
    particlePartialOverlayVideoDelta, particlePartialSegmentFramesInside, particlePartialWorker, particlePlanSuppressed, particleProjectSuppressed,
    particleSecondAdjustmentDelta, particleSourceProjectImmutable, particleWorker, rejectedNegativeControls, secondAdjustmentDelta,
    secondOverlayDelta, segmentFramesInside, sourceSnapshot, typographyDelta, worker,
    typography, adjustment,
  } = context;
const report = {
  schema: "editkin.temporal-look-project-render-gate/v1", measuredAt: new Date().toISOString(), status: "GREEN", executionMode: mixed.clip.executionMode, frameCount: mixed.clip.frameCount, losslessPixelDifferences,
  combinedContract: worker.lookContract, motionContract: worker.runtime, typographyContract: worker.typographyContract, adjustmentContract: worker.adjustmentContract,
  temporalFramesWithReceipt: mixed.clip.gpu.temporalSampling?.framesWithReceipt, maximumDistinctDecodedTimestampCount: mixed.clip.gpu.temporalSampling?.maximumDistinctDecodedTimestampCount, residentFrameRingSize: mixed.clip.gpu.temporalSampling?.residentFrameRingSize, residentBytes: mixed.clip.gpu.temporalSampling?.residentBytes,
  captionCueIds: typography.captionCueIds, motionGraphicIds: typography.motionGraphicIds, singleColourCaptions: typography.singleColourCaptions, captionTextureUploads: typography.captionTextureUploads, motionGraphicTextureUploads: typography.motionGraphicTextureUploads, framesWithActiveCaptions: typography.framesWithActiveCaptions, framesWithActiveMotionGraphics: typography.framesWithActiveMotionGraphics,
  adjustmentClipIds: adjustment.adjustmentClipIds, adjustmentNodeIds: adjustment.nodeIdsByClip["adjustment-grade"], adjustmentFramesWithReceipt: adjustment.framesWithActiveAdjustments, adjustmentExecutionMode: adjustment.executionMode,
  ...typographyDelta, ...adjustmentDelta, captionPlanSuppressed: mixed.plan.captions.length === 0, adjustmentPlanSuppressed: !mixed.plan.videoLayers.some((layer: any) => layer.segments.some((segment: any) => segment.kind === "clip" && segment.clip.id === "adjustment-grade")),
  typographyProjectSuppressed: !filteredProject.captions.length && !filteredProject.motionGraphics.length, adjustmentProjectSuppressed: !filteredProject.tracks.some((track: any) => track.clips.some((clip: any) => clip.id === "adjustment-grade")), materializedClipReset, sourceProjectImmutable: JSON.stringify(mixed.project) === sourceSnapshot,
  overlayCombinedContract: overlayWorker.lookContract, overlayCompositeContract: overlayWorker.compositeContract,
  overlayCompositeFramesWithReceipt: overlayMixed.clip.gpu.composite.framesWithReceipt,
  overlayAdjustmentBaseLayerCount: overlayMixed.clip.gpu.adjustment.baseLayerCount,
  overlayLosslessPixelDifferences, ...overlayDelta, overlayPlanSuppressed, overlayProjectSuppressed, overlaySourceProjectImmutable,
  overlayRetainedAudioClipCount: overlayMixed.plan.audioClips.length, overlayProductPathCpuPixelCopies: overlayMixed.clip.gpu.productPathCpuPixelCopies, overlayVerificationReadback: overlayMixed.clip.gpu.verificationReadback,
  multiOverlayCombinedContract: multiOverlayWorker.lookContract, multiOverlayCompositeContract: multiOverlayWorker.compositeContract,
  multiOverlayClipIds: multiOverlayWorker.overlayClipIds, multiOverlayCompositeFramesWithReceipt: multiOverlayMixed.clip.gpu.composite.framesWithReceipt,
  multiOverlayCompositeLayerCount: multiOverlayMixed.clip.gpu.composite.layerCount,
  multiOverlayAdjustmentMinimumBaseLayerCount: multiOverlayMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  multiOverlayAdjustmentMaximumBaseLayerCount: multiOverlayMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  multiOverlayLosslessPixelDifferences, ...secondOverlayDelta, multiOverlayPlanSuppressed, multiOverlayProjectSuppressed, multiOverlaySourceProjectImmutable,
  multiOverlayRetainedAudioClipCount: multiOverlayMixed.plan.audioClips.length, multiOverlayProductPathCpuPixelCopies: multiOverlayMixed.clip.gpu.productPathCpuPixelCopies, multiOverlayVerificationReadback: multiOverlayMixed.clip.gpu.verificationReadback,
  multiAdjustmentCombinedContract: multiAdjustmentWorker.lookContract, multiAdjustmentContract: multiAdjustmentWorker.adjustmentContract,
  multiAdjustmentClipIds: multiAdjustmentMixed.clip.gpu.adjustment.adjustmentClipIds,
  multiAdjustmentFramesWithReceipt: multiAdjustmentMixed.clip.gpu.adjustment.framesWithActiveAdjustments,
  multiAdjustmentTotalPasses: multiAdjustmentMixed.clip.gpu.adjustment.totalAdjustmentPasses,
  multiAdjustmentMinimumActiveCount: multiAdjustmentMixed.clip.gpu.adjustment.minimumActiveAdjustmentCount,
  multiAdjustmentMaximumActiveCount: multiAdjustmentMixed.clip.gpu.adjustment.maximumActiveAdjustmentCount,
  multiAdjustmentBaseLayerCount: multiAdjustmentMixed.clip.gpu.adjustment.baseLayerCount,
  multiAdjustmentLosslessPixelDifferences, ...secondAdjustmentDelta, multiAdjustmentPlanSuppressed, multiAdjustmentProjectSuppressed, multiAdjustmentSourceProjectImmutable,
  multiAdjustmentCaptionSingleColour: multiAdjustmentMixed.clip.gpu.typography.singleColourCaptions,
  multiAdjustmentRetainedAudioClipCount: multiAdjustmentMixed.plan.audioClips.length, multiAdjustmentProductPathCpuPixelCopies: multiAdjustmentMixed.clip.gpu.productPathCpuPixelCopies, multiAdjustmentVerificationReadback: multiAdjustmentMixed.clip.gpu.verificationReadback,
  particleCombinedContract: particleWorker.lookContract, particleContract: particleWorker.particleContract,
  particleEmitterNodeIds: particleMixed.clip.gpu.particle.emitterNodeIds,
  particleFramesWithReceipt: particleMixed.clip.gpu.particle.framesWithActiveParticles,
  particleCeiling: particleMixed.clip.gpu.particle.particleCeiling,
  particleMaximumGpuTextureWrites: particleMixed.clip.gpu.particle.maximumGpuTextureWrites,
  particleAdjustmentMinimumBaseLayerCount: particleMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particleAdjustmentMaximumBaseLayerCount: particleMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particleLosslessPixelDifferences, ...particleDelta, particlePlanSuppressed, particleProjectSuppressed, particleSourceProjectImmutable,
  particleCaptionSingleColour: particleMixed.clip.gpu.typography.singleColourCaptions,
  particleRetainedAudioClipCount: particleMixed.plan.audioClips.length, particleProductPathCpuPixelCopies: particleMixed.clip.gpu.productPathCpuPixelCopies, particleVerificationReadback: particleMixed.clip.gpu.verificationReadback,
  particleMultiAdjustmentCombinedContract: particleMultiAdjustmentWorker.lookContract,
  particleMultiAdjustmentContract: particleMultiAdjustmentWorker.adjustmentContract,
  particleMultiAdjustmentClipIds: particleMultiAdjustmentMixed.clip.gpu.adjustment.adjustmentClipIds,
  particleMultiAdjustmentFramesWithReceipt: particleMultiAdjustmentMixed.clip.gpu.adjustment.framesWithActiveAdjustments,
  particleMultiAdjustmentTotalPasses: particleMultiAdjustmentMixed.clip.gpu.adjustment.totalAdjustmentPasses,
  particleMultiAdjustmentMinimumActiveCount: particleMultiAdjustmentMixed.clip.gpu.adjustment.minimumActiveAdjustmentCount,
  particleMultiAdjustmentMaximumActiveCount: particleMultiAdjustmentMixed.clip.gpu.adjustment.maximumActiveAdjustmentCount,
  particleMultiAdjustmentMinimumBaseLayerCount: particleMultiAdjustmentMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particleMultiAdjustmentMaximumBaseLayerCount: particleMultiAdjustmentMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particleMultiAdjustmentLosslessPixelDifferences, ...particleSecondAdjustmentDelta,
  particleMultiAdjustmentPlanSuppressed, particleMultiAdjustmentProjectSuppressed, particleMultiAdjustmentSourceProjectImmutable,
  particleMultiAdjustmentCaptionSingleColour: particleMultiAdjustmentMixed.clip.gpu.typography.singleColourCaptions,
  particleMultiAdjustmentRetainedAudioClipCount: particleMultiAdjustmentMixed.plan.audioClips.length,
  particleMultiAdjustmentProductPathCpuPixelCopies: particleMultiAdjustmentMixed.clip.gpu.productPathCpuPixelCopies,
  particleMultiAdjustmentVerificationReadback: particleMultiAdjustmentMixed.clip.gpu.verificationReadback,
  particleOverlayCombinedContract: particleOverlayWorker.lookContract,
  particleOverlayParticleContract: particleOverlayWorker.particleContract,
  particleOverlayCompositeContract: particleOverlayWorker.compositeContract,
  particleOverlayAdjustmentContract: particleOverlayWorker.adjustmentContract,
  particleOverlayClipIds: particleOverlayWorker.overlayClipIds,
  particleOverlayEmitterNodeIds: particleOverlayWorker.particleNodeIds,
  particleOverlayCompositeFramesWithReceipt: particleOverlayMixed.clip.gpu.composite.framesWithReceipt,
  particleOverlayParticleFramesWithReceipt: particleOverlayMixed.clip.gpu.particle.framesWithActiveParticles,
  particleOverlayMinimumBaseLayerCount: particleOverlayMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particleOverlayMaximumBaseLayerCount: particleOverlayMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particleOverlayLosslessPixelDifferences, ...particleOverlayParticleDelta, ...particleOverlayVideoDelta,
  particleOverlayPlanSuppressed, particleOverlayProjectSuppressed, particleOverlaySourceProjectImmutable,
  particleOverlayCaptionSingleColour: particleOverlayMixed.clip.gpu.typography.singleColourCaptions,
  particleOverlayRetainedAudioClipCount: particleOverlayMixed.plan.audioClips.length,
  particleOverlayProductPathCpuPixelCopies: particleOverlayMixed.clip.gpu.productPathCpuPixelCopies,
  particleOverlayVerificationReadback: particleOverlayMixed.clip.gpu.verificationReadback,
  particleAnimatedOverlayCombinedContract: particleAnimatedOverlayWorker.lookContract,
  particleAnimatedOverlayAnimationContract: particleAnimatedOverlayWorker.overlayAnimationContract,
  particleAnimatedOverlayParticleContract: particleAnimatedOverlayWorker.particleContract,
  particleAnimatedOverlayCompositeContract: particleAnimatedOverlayWorker.compositeContract,
  particleAnimatedOverlayAdjustmentContract: particleAnimatedOverlayWorker.adjustmentContract,
  particleAnimatedOverlayAdjustmentClipIds: particleAnimatedOverlayMixed.clip.gpu.adjustment.adjustmentClipIds,
  particleAnimatedOverlayAdjustmentFramesWithReceipt: particleAnimatedOverlayMixed.clip.gpu.adjustment.framesWithActiveAdjustments,
  particleAnimatedOverlayAdjustmentTotalPasses: particleAnimatedOverlayMixed.clip.gpu.adjustment.totalAdjustmentPasses,
  particleAnimatedOverlayAdjustmentMinimumActiveCount: particleAnimatedOverlayMixed.clip.gpu.adjustment.minimumActiveAdjustmentCount,
  particleAnimatedOverlayAdjustmentMaximumActiveCount: particleAnimatedOverlayMixed.clip.gpu.adjustment.maximumActiveAdjustmentCount,
  particleAnimatedOverlayClipIds: particleAnimatedOverlayWorker.overlayAnimationClipIds,
  particleAnimatedOverlayTransformNodeIds: particleAnimatedOverlayWorker.overlayAnimationTransformNodeIds,
  particleAnimatedOverlayKeyframeCount: particleAnimatedOverlayWorker.overlayAnimationKeyframeCounts?.["clip-overlay"],
  particleAnimatedOverlayCompositeFramesWithReceipt: particleAnimatedOverlayMixed.clip.gpu.composite.framesWithReceipt,
  particleAnimatedOverlayParticleFramesWithReceipt: particleAnimatedOverlayMixed.clip.gpu.particle.framesWithActiveParticles,
  particleAnimatedOverlayMinimumBaseLayerCount: particleAnimatedOverlayMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particleAnimatedOverlayMaximumBaseLayerCount: particleAnimatedOverlayMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particleAnimatedOverlayLosslessPixelDifferences, ...particleAnimatedOverlayTransformDelta,
  particleAnimatedOverlayPlanSuppressed, particleAnimatedOverlayProjectSuppressed,
  particleAnimatedOverlaySourceProjectImmutable,
  particleAnimatedOverlayCaptionSingleColour: particleAnimatedOverlayMixed.clip.gpu.typography.singleColourCaptions,
  particleAnimatedOverlayRetainedAudioClipCount: particleAnimatedOverlayMixed.plan.audioClips.length,
  particleAnimatedOverlayProductPathCpuPixelCopies: particleAnimatedOverlayMixed.clip.gpu.productPathCpuPixelCopies,
  particleAnimatedOverlayVerificationReadback: particleAnimatedOverlayMixed.clip.gpu.verificationReadback,
  particleOverlayMultiAdjustmentCombinedContract: particleOverlayMultiAdjustmentWorker.lookContract,
  particleOverlayMultiAdjustmentParticleContract: particleOverlayMultiAdjustmentWorker.particleContract,
  particleOverlayMultiAdjustmentCompositeContract: particleOverlayMultiAdjustmentWorker.compositeContract,
  particleOverlayMultiAdjustmentContract: particleOverlayMultiAdjustmentWorker.adjustmentContract,
  particleOverlayMultiAdjustmentClipIds: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.adjustmentClipIds,
  particleOverlayMultiAdjustmentOverlayClipIds: particleOverlayMultiAdjustmentWorker.overlayClipIds,
  particleOverlayMultiAdjustmentEmitterNodeIds: particleOverlayMultiAdjustmentWorker.particleNodeIds,
  particleOverlayMultiAdjustmentFramesWithReceipt: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.framesWithActiveAdjustments,
  particleOverlayMultiAdjustmentTotalPasses: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.totalAdjustmentPasses,
  particleOverlayMultiAdjustmentMinimumActiveCount: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.minimumActiveAdjustmentCount,
  particleOverlayMultiAdjustmentMaximumActiveCount: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.maximumActiveAdjustmentCount,
  particleOverlayMultiAdjustmentCompositeFramesWithReceipt: particleOverlayMultiAdjustmentMixed.clip.gpu.composite.framesWithReceipt,
  particleOverlayMultiAdjustmentParticleFramesWithReceipt: particleOverlayMultiAdjustmentMixed.clip.gpu.particle.framesWithActiveParticles,
  particleOverlayMultiAdjustmentMinimumBaseLayerCount: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particleOverlayMultiAdjustmentMaximumBaseLayerCount: particleOverlayMultiAdjustmentMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particleOverlayMultiAdjustmentLosslessPixelDifferences, ...particleOverlaySecondAdjustmentDelta,
  particleOverlayMultiAdjustmentPlanSuppressed, particleOverlayMultiAdjustmentProjectSuppressed,
  particleOverlayMultiAdjustmentSourceProjectImmutable,
  particleOverlayMultiAdjustmentCaptionSingleColour: particleOverlayMultiAdjustmentMixed.clip.gpu.typography.singleColourCaptions,
  particleOverlayMultiAdjustmentRetainedAudioClipCount: particleOverlayMultiAdjustmentMixed.plan.audioClips.length,
  particleOverlayMultiAdjustmentProductPathCpuPixelCopies: particleOverlayMultiAdjustmentMixed.clip.gpu.productPathCpuPixelCopies,
  particleOverlayMultiAdjustmentVerificationReadback: particleOverlayMultiAdjustmentMixed.clip.gpu.verificationReadback,
  particlePartialOverlayCombinedContract: particlePartialWorker.lookContract,
  particlePartialOverlayParticleContract: particlePartialWorker.particleContract,
  particlePartialOverlayCompositeContract: particlePartialWorker.compositeContract,
  particlePartialOverlayAdjustmentContract: particlePartialWorker.adjustmentContract,
  particlePartialOverlayClipIds: particlePartialWorker.overlayClipIds,
  particlePartialOverlayEmitterNodeIds: particlePartialWorker.particleNodeIds,
  particlePartialOverlayCompositeFramesWithReceipt: particlePartialMixed.clip.gpu.composite.framesWithReceipt,
  particlePartialOverlayParticleFramesWithReceipt: particlePartialMixed.clip.gpu.particle.framesWithActiveParticles,
  particlePartialOverlayRangeStartFrame: particlePartialMixed.clip.gpu.composite.timelineRanges[0]?.timelineStartFrame,
  particlePartialOverlayRangeDurationFrames: particlePartialMixed.clip.gpu.composite.timelineRanges[0]?.durationFrames,
  particlePartialOverlayMinimumBaseLayerCount: particlePartialMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particlePartialOverlayMaximumBaseLayerCount: particlePartialMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particlePartialOverlayLosslessPixelDifferences, particlePartialOverlayInactivePixelDifferences,
  ...particlePartialOverlayParticleDelta, ...particlePartialOverlayVideoDelta,
  particlePartialOverlayPlanGapFrames: particlePartialSegmentFramesInside("gap", .2, .5),
  particlePartialOverlayPlanTailFrames: particlePartialSegmentFramesInside("clip", .5, .8),
  particlePartialOverlayProjectTail, particlePartialOverlayPlanSuppressed, particlePartialOverlayProjectSuppressed,
  particlePartialOverlaySourceProjectImmutable,
  particlePartialOverlayCaptionSingleColour: particlePartialMixed.clip.gpu.typography.singleColourCaptions,
  particlePartialOverlayRetainedAudioClipCount: particlePartialMixed.plan.audioClips.length,
  particlePartialOverlayProductPathCpuPixelCopies: particlePartialMixed.clip.gpu.productPathCpuPixelCopies,
  particlePartialOverlayVerificationReadback: particlePartialMixed.clip.gpu.verificationReadback,
  particlePartialOverlayMultiAdjustmentCombinedContract: particlePartialOverlayMultiAdjustmentWorker.lookContract,
  particlePartialOverlayMultiAdjustmentParticleContract: particlePartialOverlayMultiAdjustmentWorker.particleContract,
  particlePartialOverlayMultiAdjustmentCompositeContract: particlePartialOverlayMultiAdjustmentWorker.compositeContract,
  particlePartialOverlayMultiAdjustmentContract: particlePartialOverlayMultiAdjustmentWorker.adjustmentContract,
  particlePartialOverlayMultiAdjustmentClipIds: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.adjustmentClipIds,
  particlePartialOverlayMultiAdjustmentOverlayClipIds: particlePartialOverlayMultiAdjustmentWorker.overlayClipIds,
  particlePartialOverlayMultiAdjustmentEmitterNodeIds: particlePartialOverlayMultiAdjustmentWorker.particleNodeIds,
  particlePartialOverlayMultiAdjustmentFramesWithReceipt: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.framesWithActiveAdjustments,
  particlePartialOverlayMultiAdjustmentTotalPasses: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.totalAdjustmentPasses,
  particlePartialOverlayMultiAdjustmentMinimumActiveCount: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.minimumActiveAdjustmentCount,
  particlePartialOverlayMultiAdjustmentMaximumActiveCount: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.maximumActiveAdjustmentCount,
  particlePartialOverlayMultiAdjustmentCompositeFramesWithReceipt: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.composite.framesWithReceipt,
  particlePartialOverlayMultiAdjustmentParticleFramesWithReceipt: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.particle.framesWithActiveParticles,
  particlePartialOverlayMultiAdjustmentRangeStartFrame: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.composite.timelineRanges[0]?.timelineStartFrame,
  particlePartialOverlayMultiAdjustmentRangeDurationFrames: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.composite.timelineRanges[0]?.durationFrames,
  particlePartialOverlayMultiAdjustmentMinimumBaseLayerCount: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  particlePartialOverlayMultiAdjustmentMaximumBaseLayerCount: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  particlePartialOverlayMultiAdjustmentLosslessPixelDifferences, ...particlePartialOverlaySecondAdjustmentDelta,
  particlePartialOverlayMultiAdjustmentPlanGapFrames: particlePartialOverlayMultiAdjustmentSegmentFramesInside("gap", .2, .5),
  particlePartialOverlayMultiAdjustmentPlanTailFrames: particlePartialOverlayMultiAdjustmentSegmentFramesInside("clip", .5, .8),
  particlePartialOverlayMultiAdjustmentProjectTail, particlePartialOverlayMultiAdjustmentPlanSuppressed,
  particlePartialOverlayMultiAdjustmentProjectSuppressed, particlePartialOverlayMultiAdjustmentSourceProjectImmutable,
  particlePartialOverlayMultiAdjustmentCaptionSingleColour: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.typography.singleColourCaptions,
  particlePartialOverlayMultiAdjustmentRetainedAudioClipCount: particlePartialOverlayMultiAdjustmentMixed.plan.audioClips.length,
  particlePartialOverlayMultiAdjustmentProductPathCpuPixelCopies: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.productPathCpuPixelCopies,
  particlePartialOverlayMultiAdjustmentVerificationReadback: particlePartialOverlayMultiAdjustmentMixed.clip.gpu.verificationReadback,
  partialOverlayCombinedContract: partialWorker.lookContract, partialOverlayCompositeContract: partialWorker.compositeContract,
  partialOverlayCompositeFramesWithReceipt: partialMixed.clip.gpu.composite.framesWithReceipt,
  partialOverlayRangeStartFrame: partialMixed.clip.gpu.composite.timelineRanges[0]?.timelineStartFrame,
  partialOverlayRangeDurationFrames: partialMixed.clip.gpu.composite.timelineRanges[0]?.durationFrames,
  partialOverlayAdjustmentMinimumBaseLayerCount: partialMixed.clip.gpu.adjustment.minimumBaseLayerCount,
  partialOverlayAdjustmentMaximumBaseLayerCount: partialMixed.clip.gpu.adjustment.maximumBaseLayerCount,
  partialOverlayLosslessPixelDifferences, partialOverlayInactivePixelDifferences, ...Object.fromEntries(Object.entries(partialOverlayDelta).map(([key, value]) => [key.replace(/^overlay/, "partialOverlay"), value])),
  partialOverlayPlanGapFrames: segmentFramesInside("gap", .2, .5), partialOverlayPlanTailFrames: segmentFramesInside("clip", .5, .8), partialOverlayProjectTail,
  partialOverlayCaptionPlanSuppressed: partialMixed.plan.captions.length === 0,
  partialOverlayAdjustmentPlanSuppressed: !partialMixed.plan.videoLayers.some((layer: any) => layer.segments.some((segment: any) => segment.kind === "clip" && segment.clip.id === "adjustment-grade")),
  partialOverlayTypographyProjectSuppressed: !partialFilteredProject.captions.length && !partialFilteredProject.motionGraphics.length,
  partialOverlayAdjustmentProjectSuppressed: !partialFilteredProject.tracks.some((track: any) => track.clips.some((clip: any) => clip.id === "adjustment-grade")),
  partialOverlaySourceProjectImmutable: JSON.stringify(partialMixed.project) === partialSourceSnapshot,
  partialOverlayRetainedAudioClipCount: partialMixed.plan.audioClips.length, partialOverlayProductPathCpuPixelCopies: partialMixed.clip.gpu.productPathCpuPixelCopies, partialOverlayVerificationReadback: partialMixed.clip.gpu.verificationReadback,
  retainedAudioClipCount: mixed.plan.audioClips.length, programCount: mixed.clip.gpu.programs.length, productPathCpuPixelCopies: mixed.clip.gpu.productPathCpuPixelCopies, verificationReadback: mixed.clip.gpu.verificationReadback, rejectedNegativeControls,
  executableSha256: mixed.clip.gpu.executableSha256, stackSha256: mixed.clip.gpu.stackSha256, intermediateSha256: mixed.clip.intermediateSha256, intermediateBytes: (await stat(mixed.intermediate.assetPath)).size, firstFrameSha256: mixed.clip.gpu.firstFrameSha256, lastFrameSha256: mixed.clip.gpu.lastFrameSha256, sourceSha256: sha256(await readFile(mixed.project.assets[0].uri)),
};
  return report;
}
